---
title: "survival CNA"
author: "Noor Rizvi"
date: "2025-02-18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyr)
library(dplyr)
library(tibble)
library(survival)
library(survminer)
library(purrr)
library(pheatmap)
library(cluster)
source("../../src/init.R")

```

```{r}

# Filter clinical data for samples in dcis dataset (patients wiht RT)
cl <- cl[cl$Tumor_Sample_Barcode %in% dcis@clinical.data$sample_name[dcis@clinical.data$radiation=="TRUE"],]


# Format clinical data and cytoband data
cl$ID <- cl$Tumor_Sample_Barcode
cytoband_long <- rownames_to_column(cytoband, var = "cytoband")

cytoband_long <- pivot_longer(
  cytoband_long,
  cols = starts_with("DCRT"),  # Columns to pivot
  names_to = "ID",  # Name of the new key column
  values_to = "cna" # Name of the new value column
)

# Join clinical and cytoband data
cytoband_long <- left_join(cytoband_long, cl)

# Define gain/loss based on CNA thresholds
cytoband_long$gain <- cytoband_long$cna >0.2
cytoband_long$loss <- cytoband_long$cna < (-0.2)

```

```{r}
# Cox proportional hazards model for GCS
cox_model <- coxph(Surv(time.10, event.10.chr) ~ GCS, data = cl)
summary(cox_model)

# Cox model for nuclear grade (nugradef)
cox_model <- coxph(Surv(time.10, event.10.chr) ~ nugradef, data = cl)
summary(cox_model)
```


```{r}

# Function to analyze a single cytoband
analyze_cytoband <- function(data) {
  cytoband <- unique(data$cytoband)
  
  # Kaplan-Meier analysis for gain
  gain_analysis <- tryCatch({
    surv_fit_gain <- survfit(Surv(time.10, event.10.chr) ~ gain, data = data)
    plot_gain <- ggsurvplot(
      surv_fit_gain,
      data = data,
      pval = TRUE,
      conf.int = TRUE,
      risk.table = TRUE,
      xlab = "Time",
      ylab = "Survival probability",
      title = paste("Kaplan-Meier Curve for", cytoband, "(Gain)")
    )
    cox_model_gain <- coxph(Surv(time.10, event.10.chr) ~ gain, data = data)
    list(plot = plot_gain, cox_model = cox_model_gain)
  }, error = function(e) NULL)
  
  # Kaplan-Meier analysis for gain
  loss_analysis <- tryCatch({
    surv_fit_loss <- survfit(Surv(time.10, event.10.chr) ~ loss, data = data)
    plot_loss <- ggsurvplot(
      surv_fit_loss,
      data = data,
      pval = TRUE,
      conf.int = TRUE,
      risk.table = TRUE,
      xlab = "Time",
      ylab = "Survival probability",
      title = paste("Kaplan-Meier Curve for", cytoband, "(Loss)")
    )
    cox_model_loss <- coxph(Surv(time.10, event.10.chr) ~ loss, data = data)
    list(plot = plot_loss, cox_model = cox_model_loss)
  }, error = function(e) NULL)
  
  return(list(
    cytoband = cytoband,
    gain = gain_analysis,
    loss = loss_analysis
  ))
}


# Group data by cytoband and analyze each
results <- cytoband_long %>%
  group_by(cytoband) %>%
  group_map(~analyze_cytoband(.x), .keep = TRUE)


```


```{r}

# Function to safely extract p-values from Cox models for gain and loss
safe_extract_info <- function(x) {
  tryCatch({
    gain_pvalue <- summary(x$gain$cox_model)$coefficients["gainTRUE", "Pr(>|z|)"]
    loss_pvalue <- summary(x$loss$cox_model)$coefficients["lossTRUE", "Pr(>|z|)"]
    data.frame(
      cytoband = x$cytoband,
      gain_pvalue = gain_pvalue,
      loss_pvalue = loss_pvalue
    )
  }, error = function(e) NULL)
}

# Extract p-values for all cytobands into a single data frame
cytoband_pvalues <- map_dfr(results, safe_extract_info)


# Filter for significant cytobands
significant_cytobands <- cytoband_pvalues %>%
  mutate(
    gain_coef = map_dbl(results, ~coef(.$gain$cox_model)["gainTRUE"]),
    loss_coef = map_dbl(results, ~coef(.$loss$cox_model)["lossTRUE"]),
    gain_samples = map_int(results, ~(.$gain$plot$plot$data$n.risk[2])),
    loss_samples = map_int(results, ~(.$loss$plot$plot$data$n.risk[2]))) %>%
  filter(
    (!is.na(gain_pvalue) & gain_pvalue < 0.05 & gain_coef > 0 & gain_samples >= 10) |
    (!is.na(loss_pvalue) & loss_pvalue < 0.05 & loss_coef > 0 & loss_samples >= 10)
  )

print(significant_cytobands)
```
